"""Stable error codes for gate, registry, and CLI."""

from __future__ import annotations

# Gate
PHASE0_NOT_COMPLETE = "PHASE0_NOT_COMPLETE"
TASK_PLAN_PHASE_NOT_MARKED = "TASK_PLAN_PHASE_NOT_MARKED"
MISSING_CONCEPT_BRIEF = "MISSING_CONCEPT_BRIEF"
MISSING_PROJECT_JSON = "MISSING_PROJECT_JSON"
MISSING_PROGRESS_JSON = "MISSING_PROGRESS_JSON"
MISSING_CHARACTER_PROFILES = "MISSING_CHARACTER_PROFILES"
MISSING_WORLDBUILDING = "MISSING_WORLDBUILDING"
MISSING_CHAPTER = "MISSING_CHAPTER"
OPEN_REVIEW_BLOCKERS = "OPEN_REVIEW_BLOCKERS"
GATE_FAIL = "GATE_FAIL"

# Registry / paths
SUITE_ROOT_NOT_FOUND = "SUITE_ROOT_NOT_FOUND"
UNKNOWN_NOVEL_SLUG = "UNKNOWN_NOVEL_SLUG"
NO_ACTIVE_NOVEL = "NO_ACTIVE_NOVEL"
PROJECT_PATH_OUT_OF_BOUNDS = "PROJECT_PATH_OUT_OF_BOUNDS"

# Doctor
DOCTOR_FAIL = "DOCTOR_FAIL"
DOCTOR_CORE_FAIL = "DOCTOR_CORE_FAIL"

# Product layer (novel-suite/)
PRODUCT_INVALID_CATEGORY = "PRODUCT_INVALID_CATEGORY"
PRODUCT_INVALID_NAME = "PRODUCT_INVALID_NAME"
PRODUCT_NOT_FOUND = "PRODUCT_NOT_FOUND"
PRODUCT_PATH_TRAVERSAL = "PRODUCT_PATH_TRAVERSAL"
PRODUCT_VALIDATE_FAIL = "PRODUCT_VALIDATE_FAIL"

# Chapter
GATE_PHASE5_BLOCKED = "GATE_PHASE5_BLOCKED"
CHAPTER_INPUT_NOT_FOUND = "CHAPTER_INPUT_NOT_FOUND"
CHAPTER_INPUT_OUT_OF_BOUNDS = "CHAPTER_INPUT_OUT_OF_BOUNDS"
CHAPTER_ALREADY_EXISTS = "CHAPTER_ALREADY_EXISTS"
SNAPSHOT_INPUT_NOT_FOUND = "SNAPSHOT_INPUT_NOT_FOUND"
INVALID_CHAPTER_NUMBER = "INVALID_CHAPTER_NUMBER"
SKIP_GATE_NOT_ALLOWED = "SKIP_GATE_NOT_ALLOWED"
DRAFT_NOT_FOUND = "DRAFT_NOT_FOUND"
PROJECT_NOT_FOUND = "PROJECT_NOT_FOUND"

ENV_ALLOW_SKIP_GATE = "NOVEL_SUITE_ALLOW_SKIP_GATE"

# Intel scan
SCAN_NO_HITS = "SCAN_NO_HITS"
SCAN_INPUT_NOT_FOUND = "SCAN_INPUT_NOT_FOUND"
SCAN_INVALID_PLATFORMS = "SCAN_INVALID_PLATFORMS"
SCAN_LIVE_BLOCKED = "SCAN_LIVE_BLOCKED"
DEMO_FIXTURE_MISSING = "DEMO_FIXTURE_MISSING"

# Init
INIT_OK = "INIT_OK"
CONCEPT_NOT_FOUND = "CONCEPT_NOT_FOUND"
INIT_TITLE_REQUIRED = "INIT_TITLE_REQUIRED"
INIT_PREMISE_REQUIRED = "INIT_PREMISE_REQUIRED"
INIT_SCAFFOLD_FAILED = "INIT_SCAFFOLD_FAILED"
INIT_FROM_SCAN_FAILED = "INIT_FROM_SCAN_FAILED"
SCAN_JSON_NOT_FOUND = "SCAN_JSON_NOT_FOUND"
SCAN_JSON_INVALID = "SCAN_JSON_INVALID"
CLEAN_OK = "CLEAN_OK"
CLEAN_DRY_RUN_OK = "CLEAN_DRY_RUN_OK"
INIT_PATH_ERROR = "INIT_PATH_ERROR"

# Export
EXPORT_OK = "EXPORT_OK"
EXPORT_BLOCKED = "EXPORT_BLOCKED"
EXPORT_FAILED = "EXPORT_FAILED"
INVALID_EXPORT_FORMAT = "INVALID_EXPORT_FORMAT"
GATE_PHASE9_BLOCKED = "GATE_PHASE9_BLOCKED"
EPUB_DEPENDENCY_MISSING = "EPUB_DEPENDENCY_MISSING"

# Video jobs (Phase G)
VIDEO_CREATE_OK = "VIDEO_CREATE_OK"
VIDEO_STATUS_OK = "VIDEO_STATUS_OK"
VIDEO_STATUS_FAILED = "VIDEO_STATUS_FAILED"
VIDEO_RUN_OK = "VIDEO_RUN_OK"
VIDEO_RUN_FAILED = "VIDEO_RUN_FAILED"
VIDEO_JOB_NOT_FOUND = "VIDEO_JOB_NOT_FOUND"
VIDEO_CHAPTER_NOT_FOUND = "VIDEO_CHAPTER_NOT_FOUND"
VIDEO_RESUME_BLOCKED = "VIDEO_RESUME_BLOCKED"

# Storyboard (Sprint 2.1)
STORYBOARD_OK = "STORYBOARD_OK"
STORYBOARD_FAILED = "STORYBOARD_FAILED"
STORYBOARD_SCHEMA_INVALID = "STORYBOARD_SCHEMA_INVALID"
STORYBOARD_LLM_UNAVAILABLE = "STORYBOARD_LLM_UNAVAILABLE"

# Character assets (Sprint 2.2)
CHARACTER_LIST_OK = "CHARACTER_LIST_OK"
CHARACTER_CVDP_NOT_FOUND = "CHARACTER_CVDP_NOT_FOUND"
CHARACTER_PACK_OK = "CHARACTER_PACK_OK"
CHARACTER_RENDERER_UNAVAILABLE = "CHARACTER_RENDERER_UNAVAILABLE"
CHARACTER_QC_OK = "CHARACTER_QC_OK"
CHARACTER_QC_FAILED = "CHARACTER_QC_FAILED"

# Stills (Sprint 2.3a)
STILLS_GENERATE_OK = "STILLS_GENERATE_OK"
STILLS_STORYBOARD_MISSING = "STILLS_STORYBOARD_MISSING"
STILLS_NO_SCENES = "STILLS_NO_SCENES"
STILLS_RENDER_FAILED = "STILLS_RENDER_FAILED"

# Compose (Sprint 2.3b)
COMPOSE_OK = "COMPOSE_OK"
COMPOSE_STORYBOARD_MISSING = "COMPOSE_STORYBOARD_MISSING"
COMPOSE_STILLS_MISSING = "COMPOSE_STILLS_MISSING"
COMPOSE_NO_SCENES = "COMPOSE_NO_SCENES"
COMPOSE_NO_SEGMENTS = "COMPOSE_NO_SEGMENTS"
COMPOSE_FFMPEG_MISSING = "COMPOSE_FFMPEG_MISSING"
COMPOSE_STORYBOARD_INVALID = "COMPOSE_STORYBOARD_INVALID"
COMPOSE_CONCAT_PATH_INVALID = "COMPOSE_CONCAT_PATH_INVALID"
COMPOSE_FAILED = "COMPOSE_FAILED"

# Pipeline (Sprint 2.3c)
PIPELINE_OK = "PIPELINE_OK"
PIPELINE_STORYBOARD_MISSING = "PIPELINE_STORYBOARD_MISSING"

# Gate (Sprint 3 Day 3)
GATE_OK = "GATE_OK"
GATE_FAILED = "GATE_FAILED"
GATE_VIDEO_NOT_FOUND = "GATE_VIDEO_NOT_FOUND"

# Publish (Sprint 3 Day 6-10)
PUBLISH_OK = "PUBLISH_OK"
PUBLISH_FAILED = "PUBLISH_FAILED"
PUBLISH_VIDEO_NOT_FOUND = "PUBLISH_VIDEO_NOT_FOUND"
PUBLISH_PLATFORM_UNSUPPORTED = "PUBLISH_PLATFORM_UNSUPPORTED"
PUBLISH_GATE_BLOCKED = "PUBLISH_GATE_BLOCKED"
PUBLISH_LIST_OK = "PUBLISH_LIST_OK"
PUBLISH_PROJECT_NOT_FOUND = "PUBLISH_PROJECT_NOT_FOUND"
COOKIE_OK = "COOKIE_OK"
COOKIE_EXPIRED = "COOKIE_EXPIRED"

# Auth / Platform (Sprint 4 Phase A)
AUTH_LOGIN_OK = "AUTH_LOGIN_OK"
AUTH_LOGIN_FAILED = "AUTH_LOGIN_FAILED"
AUTH_LOGOUT_OK = "AUTH_LOGOUT_OK"
AUTH_STATUS_OK = "AUTH_STATUS_OK"
AUTH_STATUS_EMPTY = "AUTH_STATUS_EMPTY"
PLATFORM_UNKNOWN = "PLATFORM_UNKNOWN"
PLATFORM_INVALID = "PLATFORM_INVALID"

# MCP (Sprint 4 Phase C)
MCP_SERVE_OK = "MCP_SERVE_OK"
MCP_SDK_MISSING = "MCP_SDK_MISSING"
MCP_CONFIG_MISSING = "MCP_CONFIG_MISSING"

# Memory (Sprint 1 / SOLO node 3)
MEMORY_STORE_OK = "MEMORY_STORE_OK"
MEMORY_SEARCH_OK = "MEMORY_SEARCH_OK"
MEMORY_CHECK_OK = "MEMORY_CHECK_OK"
MEMORY_CHECK_CONFLICT = "MEMORY_CHECK_CONFLICT"
MEMORY_STATUS_OK = "MEMORY_STATUS_OK"
MEMORY_TEXT_EMPTY = "MEMORY_TEXT_EMPTY"
MEMORY_QUERY_EMPTY = "MEMORY_QUERY_EMPTY"
MEMORY_INVALID_LAYER = "MEMORY_INVALID_LAYER"
MEMORY_PROBE_OK = "MEMORY_PROBE_OK"
MEMORY_SYNC_OK = "MEMORY_SYNC_OK"
MEMORY_QDRANT_UNAVAILABLE = "MEMORY_QDRANT_UNAVAILABLE"

# Video production adapters (C5 dry-run skeleton)
VIDEO_PRODUCTION_ADAPTER_DRY_RUN_OK = "VIDEO_PRODUCTION_ADAPTER_DRY_RUN_OK"
VIDEO_PRODUCTION_ADAPTER_DRY_RUN_FAIL = "VIDEO_PRODUCTION_ADAPTER_DRY_RUN_FAIL"
VIDEO_PRODUCTION_ADAPTER_POLICY_VIOLATION = "VIDEO_PRODUCTION_ADAPTER_POLICY_VIOLATION"
VIDEO_PRODUCTION_ADAPTER_UNKNOWN = "VIDEO_PRODUCTION_ADAPTER_UNKNOWN"
VIDEO_PRODUCTION_EXAMPLE_NOT_FOUND = "VIDEO_PRODUCTION_EXAMPLE_NOT_FOUND"
VIDEO_PRODUCTION_EXAMPLE_INVALID = "VIDEO_PRODUCTION_EXAMPLE_INVALID"
VIDEO_PRODUCTION_OUTPUT_OUT_OF_BOUNDS = "VIDEO_PRODUCTION_OUTPUT_OUT_OF_BOUNDS"

# Commercial preflight (C6/C7)
COMMERCIAL_REVIEW_VALIDATE_OK = "COMMERCIAL_REVIEW_VALIDATE_OK"
COMMERCIAL_REVIEW_VALIDATE_FAIL = "COMMERCIAL_REVIEW_VALIDATE_FAIL"
CANDIDATE_GATE_VALIDATE_OK = "CANDIDATE_GATE_VALIDATE_OK"
CANDIDATE_GATE_VALIDATE_FAIL = "CANDIDATE_GATE_VALIDATE_FAIL"

# Workflow contracts (F2)
WORKFLOW_CONTRACT_VALIDATE_OK = "WORKFLOW_CONTRACT_VALIDATE_OK"
WORKFLOW_CONTRACT_VALIDATE_FAIL = "WORKFLOW_CONTRACT_VALIDATE_FAIL"
WORKFLOW_CONTRACT_NOT_FOUND = "WORKFLOW_CONTRACT_NOT_FOUND"
WORKFLOW_CONTRACT_INVALID_NAME = "WORKFLOW_CONTRACT_INVALID_NAME"

# Trace/state (F3) + multi-IDE trials (C10)
TRACE_STATE_VALIDATE_OK = "TRACE_STATE_VALIDATE_OK"
TRACE_STATE_VALIDATE_FAIL = "TRACE_STATE_VALIDATE_FAIL"
MULTI_IDE_TRIALS_VALIDATE_OK = "MULTI_IDE_TRIALS_VALIDATE_OK"
MULTI_IDE_TRIALS_VALIDATE_FAIL = "MULTI_IDE_TRIALS_VALIDATE_FAIL"

# Future backends (F4/F5) + trial feedback review (C11)
FUTURE_BACKENDS_VALIDATE_OK = "FUTURE_BACKENDS_VALIDATE_OK"
FUTURE_BACKENDS_VALIDATE_FAIL = "FUTURE_BACKENDS_VALIDATE_FAIL"
TRIAL_FEEDBACK_REVIEW_VALIDATE_OK = "TRIAL_FEEDBACK_REVIEW_VALIDATE_OK"
TRIAL_FEEDBACK_REVIEW_VALIDATE_FAIL = "TRIAL_FEEDBACK_REVIEW_VALIDATE_FAIL"

# Delivery readiness (G1/G2/G3)
DELIVERY_HUB_VALIDATE_OK = "DELIVERY_HUB_VALIDATE_OK"
DELIVERY_HUB_VALIDATE_FAIL = "DELIVERY_HUB_VALIDATE_FAIL"
DEMO_ROADMAP_VALIDATE_OK = "DEMO_ROADMAP_VALIDATE_OK"
DEMO_ROADMAP_VALIDATE_FAIL = "DEMO_ROADMAP_VALIDATE_FAIL"
LEGAL_RELEASE_REVIEW_VALIDATE_OK = "LEGAL_RELEASE_REVIEW_VALIDATE_OK"
LEGAL_RELEASE_REVIEW_VALIDATE_FAIL = "LEGAL_RELEASE_REVIEW_VALIDATE_FAIL"

# Human trial / freeze / legal packet (H1/H2/H3)
HUMAN_TRIAL_RUNBOOK_VALIDATE_OK = "HUMAN_TRIAL_RUNBOOK_VALIDATE_OK"
HUMAN_TRIAL_RUNBOOK_VALIDATE_FAIL = "HUMAN_TRIAL_RUNBOOK_VALIDATE_FAIL"
PACKAGE_FREEZE_CANDIDATE_VALIDATE_OK = "PACKAGE_FREEZE_CANDIDATE_VALIDATE_OK"
PACKAGE_FREEZE_CANDIDATE_VALIDATE_FAIL = "PACKAGE_FREEZE_CANDIDATE_VALIDATE_FAIL"
LEGAL_REVIEW_PACKET_VALIDATE_OK = "LEGAL_REVIEW_PACKET_VALIDATE_OK"
LEGAL_REVIEW_PACKET_VALIDATE_FAIL = "LEGAL_REVIEW_PACKET_VALIDATE_FAIL"

# Trial intake / freeze alignment / legal response (I1/I2/I3)
TRIAL_RESULTS_INTAKE_VALIDATE_OK = "TRIAL_RESULTS_INTAKE_VALIDATE_OK"
TRIAL_RESULTS_INTAKE_VALIDATE_FAIL = "TRIAL_RESULTS_INTAKE_VALIDATE_FAIL"
FREEZE_VERSION_ALIGNMENT_VALIDATE_OK = "FREEZE_VERSION_ALIGNMENT_VALIDATE_OK"
FREEZE_VERSION_ALIGNMENT_VALIDATE_FAIL = "FREEZE_VERSION_ALIGNMENT_VALIDATE_FAIL"
LEGAL_REVIEW_RESPONSE_INTAKE_VALIDATE_OK = "LEGAL_REVIEW_RESPONSE_INTAKE_VALIDATE_OK"
LEGAL_REVIEW_RESPONSE_INTAKE_VALIDATE_FAIL = "LEGAL_REVIEW_RESPONSE_INTAKE_VALIDATE_FAIL"

# First trial / freeze meeting / legal meeting (J1/J2/J3)
FIRST_TRIAL_SESSION_KIT_VALIDATE_OK = "FIRST_TRIAL_SESSION_KIT_VALIDATE_OK"
FIRST_TRIAL_SESSION_KIT_VALIDATE_FAIL = "FIRST_TRIAL_SESSION_KIT_VALIDATE_FAIL"
FREEZE_REVIEW_MEETING_VALIDATE_OK = "FREEZE_REVIEW_MEETING_VALIDATE_OK"
FREEZE_REVIEW_MEETING_VALIDATE_FAIL = "FREEZE_REVIEW_MEETING_VALIDATE_FAIL"
LEGAL_REVIEW_MEETING_VALIDATE_OK = "LEGAL_REVIEW_MEETING_VALIDATE_OK"
LEGAL_REVIEW_MEETING_VALIDATE_FAIL = "LEGAL_REVIEW_MEETING_VALIDATE_FAIL"

# Trial/freeze/legal decision records (K1/K2/K3)
TRIAL_RESULT_REVIEW_VALIDATE_OK = "TRIAL_RESULT_REVIEW_VALIDATE_OK"
TRIAL_RESULT_REVIEW_VALIDATE_FAIL = "TRIAL_RESULT_REVIEW_VALIDATE_FAIL"
FREEZE_DECISION_RECORD_VALIDATE_OK = "FREEZE_DECISION_RECORD_VALIDATE_OK"
FREEZE_DECISION_RECORD_VALIDATE_FAIL = "FREEZE_DECISION_RECORD_VALIDATE_FAIL"
LEGAL_DECISION_RECORD_VALIDATE_OK = "LEGAL_DECISION_RECORD_VALIDATE_OK"
LEGAL_DECISION_RECORD_VALIDATE_FAIL = "LEGAL_DECISION_RECORD_VALIDATE_FAIL"

# Import preflight (L1/L2/L3)
TRIAL_RESULT_IMPORT_PREFLIGHT_VALIDATE_OK = "TRIAL_RESULT_IMPORT_PREFLIGHT_VALIDATE_OK"
TRIAL_RESULT_IMPORT_PREFLIGHT_VALIDATE_FAIL = "TRIAL_RESULT_IMPORT_PREFLIGHT_VALIDATE_FAIL"
FREEZE_DECISION_IMPORT_PREFLIGHT_VALIDATE_OK = "FREEZE_DECISION_IMPORT_PREFLIGHT_VALIDATE_OK"
FREEZE_DECISION_IMPORT_PREFLIGHT_VALIDATE_FAIL = "FREEZE_DECISION_IMPORT_PREFLIGHT_VALIDATE_FAIL"
LEGAL_DECISION_IMPORT_PREFLIGHT_VALIDATE_OK = "LEGAL_DECISION_IMPORT_PREFLIGHT_VALIDATE_OK"
LEGAL_DECISION_IMPORT_PREFLIGHT_VALIDATE_FAIL = "LEGAL_DECISION_IMPORT_PREFLIGHT_VALIDATE_FAIL"

# Import decision records / board (M1/M2/M3)
TRIAL_IMPORT_DECISION_RECORD_VALIDATE_OK = "TRIAL_IMPORT_DECISION_RECORD_VALIDATE_OK"
TRIAL_IMPORT_DECISION_RECORD_VALIDATE_FAIL = "TRIAL_IMPORT_DECISION_RECORD_VALIDATE_FAIL"
FREEZE_IMPORT_DECISION_RECORD_VALIDATE_OK = "FREEZE_IMPORT_DECISION_RECORD_VALIDATE_OK"
FREEZE_IMPORT_DECISION_RECORD_VALIDATE_FAIL = "FREEZE_IMPORT_DECISION_RECORD_VALIDATE_FAIL"
LEGAL_IMPORT_DECISION_BOARD_VALIDATE_OK = "LEGAL_IMPORT_DECISION_BOARD_VALIDATE_OK"
LEGAL_IMPORT_DECISION_BOARD_VALIDATE_FAIL = "LEGAL_IMPORT_DECISION_BOARD_VALIDATE_FAIL"

# Decision fill kits / board execution (N1/N2/N3)
TRIAL_DECISION_FILL_KIT_VALIDATE_OK = "TRIAL_DECISION_FILL_KIT_VALIDATE_OK"
TRIAL_DECISION_FILL_KIT_VALIDATE_FAIL = "TRIAL_DECISION_FILL_KIT_VALIDATE_FAIL"
FREEZE_DECISION_FILL_KIT_VALIDATE_OK = "FREEZE_DECISION_FILL_KIT_VALIDATE_OK"
FREEZE_DECISION_FILL_KIT_VALIDATE_FAIL = "FREEZE_DECISION_FILL_KIT_VALIDATE_FAIL"
LEGAL_BOARD_EXECUTION_KIT_VALIDATE_OK = "LEGAL_BOARD_EXECUTION_KIT_VALIDATE_OK"
LEGAL_BOARD_EXECUTION_KIT_VALIDATE_FAIL = "LEGAL_BOARD_EXECUTION_KIT_VALIDATE_FAIL"
SOLO_FOUNDER_FREEZE_SELF_CHECK_VALIDATE_OK = "SOLO_FOUNDER_FREEZE_SELF_CHECK_VALIDATE_OK"
SOLO_FOUNDER_FREEZE_SELF_CHECK_VALIDATE_FAIL = "SOLO_FOUNDER_FREEZE_SELF_CHECK_VALIDATE_FAIL"
SOLO_FOUNDER_COMPLIANCE_SELF_CHECK_VALIDATE_OK = "SOLO_FOUNDER_COMPLIANCE_SELF_CHECK_VALIDATE_OK"
SOLO_FOUNDER_COMPLIANCE_SELF_CHECK_VALIDATE_FAIL = "SOLO_FOUNDER_COMPLIANCE_SELF_CHECK_VALIDATE_FAIL"
SOLO_FOUNDER_RELEASE_BLOCKED_DECLARATION_VALIDATE_OK = "SOLO_FOUNDER_RELEASE_BLOCKED_DECLARATION_VALIDATE_OK"
SOLO_FOUNDER_RELEASE_BLOCKED_DECLARATION_VALIDATE_FAIL = "SOLO_FOUNDER_RELEASE_BLOCKED_DECLARATION_VALIDATE_FAIL"
SOLO_DEMO_15MIN_VALIDATE_OK = "SOLO_DEMO_15MIN_VALIDATE_OK"
SOLO_DEMO_15MIN_VALIDATE_FAIL = "SOLO_DEMO_15MIN_VALIDATE_FAIL"
PROMPTPACK_FIRST_RUN_VALIDATE_OK = "PROMPTPACK_FIRST_RUN_VALIDATE_OK"
PROMPTPACK_FIRST_RUN_VALIDATE_FAIL = "PROMPTPACK_FIRST_RUN_VALIDATE_FAIL"
MULTI_IDE_DRY_RUN_FEEDBACK_VALIDATE_OK = "MULTI_IDE_DRY_RUN_FEEDBACK_VALIDATE_OK"
MULTI_IDE_DRY_RUN_FEEDBACK_VALIDATE_FAIL = "MULTI_IDE_DRY_RUN_FEEDBACK_VALIDATE_FAIL"
SOLO_DEMO_TRIAL_INTAKE_VALIDATE_OK = "SOLO_DEMO_TRIAL_INTAKE_VALIDATE_OK"
SOLO_DEMO_TRIAL_INTAKE_VALIDATE_FAIL = "SOLO_DEMO_TRIAL_INTAKE_VALIDATE_FAIL"
PROMPTPACK_FRICTION_REVIEW_VALIDATE_OK = "PROMPTPACK_FRICTION_REVIEW_VALIDATE_OK"
PROMPTPACK_FRICTION_REVIEW_VALIDATE_FAIL = "PROMPTPACK_FRICTION_REVIEW_VALIDATE_FAIL"
MULTI_IDE_FEEDBACK_BACKLOG_VALIDATE_OK = "MULTI_IDE_FEEDBACK_BACKLOG_VALIDATE_OK"
MULTI_IDE_FEEDBACK_BACKLOG_VALIDATE_FAIL = "MULTI_IDE_FEEDBACK_BACKLOG_VALIDATE_FAIL"
OPENCLAW_FEEDBACK_CONSOLIDATION_VALIDATE_OK = "OPENCLAW_FEEDBACK_CONSOLIDATION_VALIDATE_OK"
OPENCLAW_FEEDBACK_CONSOLIDATION_VALIDATE_FAIL = "OPENCLAW_FEEDBACK_CONSOLIDATION_VALIDATE_FAIL"
AGENT_ENTRY_MENU_VALIDATE_OK = "AGENT_ENTRY_MENU_VALIDATE_OK"
AGENT_ENTRY_MENU_VALIDATE_FAIL = "AGENT_ENTRY_MENU_VALIDATE_FAIL"
AGENT_ENTRY_MENU_LIST_OK = "AGENT_ENTRY_MENU_LIST_OK"
SERVER_VALIDATE_OK = "SERVER_VALIDATE_OK"
SERVER_VALIDATE_FAIL = "SERVER_VALIDATE_FAIL"
SERVER_RUN_OK = "SERVER_RUN_OK"
IP_PRODUCTION_DEMO_VALIDATE_OK = "IP_PRODUCTION_DEMO_VALIDATE_OK"
IP_PRODUCTION_DEMO_VALIDATE_FAIL = "IP_PRODUCTION_DEMO_VALIDATE_FAIL"
IP_PRODUCTION_DEMO_RUN_OK = "IP_PRODUCTION_DEMO_RUN_OK"
NOVEL_REVIEW_DEMO_VALIDATE_OK = "NOVEL_REVIEW_DEMO_VALIDATE_OK"
NOVEL_REVIEW_DEMO_VALIDATE_FAIL = "NOVEL_REVIEW_DEMO_VALIDATE_FAIL"
NOVEL_REVIEW_DEMO_RUN_OK = "NOVEL_REVIEW_DEMO_RUN_OK"
REALGEN_DEMO_VALIDATE_OK = "REALGEN_DEMO_VALIDATE_OK"
REALGEN_DEMO_VALIDATE_FAIL = "REALGEN_DEMO_VALIDATE_FAIL"
REALGEN_DEMO_RUN_OK = "REALGEN_DEMO_RUN_OK"
REALGEN_DEMO_SEED_MISSING = "REALGEN_DEMO_SEED_MISSING"

REALPIPELINE_VALIDATE_OK = "REALPIPELINE_VALIDATE_OK"
REALPIPELINE_VALIDATE_FAIL = "REALPIPELINE_VALIDATE_FAIL"
REALPIPELINE_RUN_OK = "REALPIPELINE_RUN_OK"

# Analytics (Sprint 6)
ANALYTICS_RECORD_OK = "ANALYTICS_RECORD_OK"
ANALYTICS_STATUS_OK = "ANALYTICS_STATUS_OK"
ANALYTICS_REPORT_OK = "ANALYTICS_REPORT_OK"
ANALYTICS_CROSS_OK = "ANALYTICS_CROSS_OK"
ANALYTICS_INVALID_METRIC = "ANALYTICS_INVALID_METRIC"
ANALYTICS_NO_METRICS = "ANALYTICS_NO_METRICS"
ANALYTICS_NO_PROJECTS = "ANALYTICS_NO_PROJECTS"
