"""Stable error codes for gate, registry, and CLI."""

from __future__ import annotations

# Gate
PHASE0_NOT_COMPLETE = "PHASE0_NOT_COMPLETE"
TASK_PLAN_PHASE_NOT_MARKED = "TASK_PLAN_PHASE_NOT_MARKED"
MISSING_CONCEPT_BRIEF = "MISSING_CONCEPT_BRIEF"
MISSING_PROJECT_JSON = "MISSING_PROJECT_JSON"
MISSING_PROGRESS_JSON = "MISSING_PROGRESS_JSON"
MISSING_CHARACTER_PROFILES = "MISSING_CHARACTER_PROFILES"
MISSING_WORLDBUILDING = "MISSING_WORLDBUILDING"
MISSING_CHAPTER = "MISSING_CHAPTER"
OPEN_REVIEW_BLOCKERS = "OPEN_REVIEW_BLOCKERS"
GATE_FAIL = "GATE_FAIL"

# Registry / paths
SUITE_ROOT_NOT_FOUND = "SUITE_ROOT_NOT_FOUND"
UNKNOWN_NOVEL_SLUG = "UNKNOWN_NOVEL_SLUG"
NO_ACTIVE_NOVEL = "NO_ACTIVE_NOVEL"
PROJECT_PATH_OUT_OF_BOUNDS = "PROJECT_PATH_OUT_OF_BOUNDS"

# Doctor
DOCTOR_FAIL = "DOCTOR_FAIL"

# Chapter
GATE_PHASE5_BLOCKED = "GATE_PHASE5_BLOCKED"
CHAPTER_INPUT_NOT_FOUND = "CHAPTER_INPUT_NOT_FOUND"
CHAPTER_INPUT_OUT_OF_BOUNDS = "CHAPTER_INPUT_OUT_OF_BOUNDS"
CHAPTER_ALREADY_EXISTS = "CHAPTER_ALREADY_EXISTS"
SNAPSHOT_INPUT_NOT_FOUND = "SNAPSHOT_INPUT_NOT_FOUND"
INVALID_CHAPTER_NUMBER = "INVALID_CHAPTER_NUMBER"
SKIP_GATE_NOT_ALLOWED = "SKIP_GATE_NOT_ALLOWED"
DRAFT_NOT_FOUND = "DRAFT_NOT_FOUND"
PROJECT_NOT_FOUND = "PROJECT_NOT_FOUND"

ENV_ALLOW_SKIP_GATE = "NOVEL_SUITE_ALLOW_SKIP_GATE"

# Intel scan
SCAN_NO_HITS = "SCAN_NO_HITS"
SCAN_INPUT_NOT_FOUND = "SCAN_INPUT_NOT_FOUND"
SCAN_INVALID_PLATFORMS = "SCAN_INVALID_PLATFORMS"
DEMO_FIXTURE_MISSING = "DEMO_FIXTURE_MISSING"

# Init
INIT_OK = "INIT_OK"
CONCEPT_NOT_FOUND = "CONCEPT_NOT_FOUND"
INIT_TITLE_REQUIRED = "INIT_TITLE_REQUIRED"
INIT_PREMISE_REQUIRED = "INIT_PREMISE_REQUIRED"
INIT_SCAFFOLD_FAILED = "INIT_SCAFFOLD_FAILED"
INIT_PATH_ERROR = "INIT_PATH_ERROR"

# Export
EXPORT_OK = "EXPORT_OK"
EXPORT_BLOCKED = "EXPORT_BLOCKED"
EXPORT_FAILED = "EXPORT_FAILED"
INVALID_EXPORT_FORMAT = "INVALID_EXPORT_FORMAT"
GATE_PHASE9_BLOCKED = "GATE_PHASE9_BLOCKED"
EPUB_DEPENDENCY_MISSING = "EPUB_DEPENDENCY_MISSING"

# Video jobs (Phase G)
VIDEO_CREATE_OK = "VIDEO_CREATE_OK"
VIDEO_STATUS_OK = "VIDEO_STATUS_OK"
VIDEO_STATUS_FAILED = "VIDEO_STATUS_FAILED"
VIDEO_RUN_OK = "VIDEO_RUN_OK"
VIDEO_RUN_FAILED = "VIDEO_RUN_FAILED"
VIDEO_JOB_NOT_FOUND = "VIDEO_JOB_NOT_FOUND"
VIDEO_CHAPTER_NOT_FOUND = "VIDEO_CHAPTER_NOT_FOUND"
VIDEO_RESUME_BLOCKED = "VIDEO_RESUME_BLOCKED"

# Memory (Sprint 1 / SOLO node 3)
MEMORY_STORE_OK = "MEMORY_STORE_OK"
MEMORY_SEARCH_OK = "MEMORY_SEARCH_OK"
MEMORY_CHECK_OK = "MEMORY_CHECK_OK"
MEMORY_CHECK_CONFLICT = "MEMORY_CHECK_CONFLICT"
MEMORY_STATUS_OK = "MEMORY_STATUS_OK"
MEMORY_TEXT_EMPTY = "MEMORY_TEXT_EMPTY"
MEMORY_QUERY_EMPTY = "MEMORY_QUERY_EMPTY"
MEMORY_INVALID_LAYER = "MEMORY_INVALID_LAYER"
MEMORY_PROBE_OK = "MEMORY_PROBE_OK"
MEMORY_SYNC_OK = "MEMORY_SYNC_OK"
MEMORY_QDRANT_UNAVAILABLE = "MEMORY_QDRANT_UNAVAILABLE"
